eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

microservice:
  payment-service:
    endpoints:
      uri: http://PAYMENT-SERVICE/payment/doPayment
  order-service:
    endpoints:
      uri: http://ORDER-SERVICE/order/bookOrder
